name: Deploy to Ec2 With Docker
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Docker Image
      working-directory: .
      run: docker build -t jihyeon27/ordersystem:latest .
    
    - name: DockerHub Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image to DockerHub
      run: docker push jihyeon27/ordersystem:latest

    # github actions 실행 전에 docker-compose파일 scp 전송 후 실행 -> 새로운 이미지 생성시 spring컨테이너만 재실행
    - name: instance1 ec2 ssh login and docker run
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST1 }}
        username: ubuntu
        key: ${{ secrets.EC2_PEMKEY }}
        script: |
          if ! type docker > /dev/null ; then
            export DEBIAN_FRONTEND=noninteractive
            curl -fsSL https://get.docker.com | bash
          fi

          if ! type docker-compose > /dev/null 2>&1; then
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
          fi

          sudo docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

          sudo docker pull jihyeon27/ordersystem:latest

          sudo docker-compose up -d --force-recreate myordersystem
